## Exercise 1: NumPy: Create an array with values ranging from 50 to 100

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


In [1]:
import numpy as np

In [2]:
array1 = np.arange(50, 101)
print(array1)

[ 50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65  66  67
  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83  84  85
  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100]


## Exercise 2: Add a border around an existing array
##### Hint: np.pad()

In [7]:
array1 = np.arange(1,17).reshape(4,4)
array2 = np.pad(array1, pad_width=1, mode='constant', constant_values = 0)
print(array2)

[[ 0  0  0  0  0  0]
 [ 0  1  2  3  4  0]
 [ 0  5  6  7  8  0]
 [ 0  9 10 11 12  0]
 [ 0 13 14 15 16  0]
 [ 0  0  0  0  0  0]]


## Exercise 3: Convert a list and tuple into arrays

List to array: 
[1 2 3 4 5 6 7 8]
Tuple to array: 
[[8 4 6]
 [1 2 3]]


In [14]:
list1 = [1,2,3,4,5,6,7,8]
array1 = np.array(list1)
print(array1)

tuple1 = (8,4,6,1,2,3)
array2 = np.array(tuple1).reshape(2,3)
print(array2)

tuple2 = ([8,4,6],[1,2,3])
array3 = np.array(tuple2)
print(array3)

#using asarray

list2 = [1,2,3,4,5,6,7,8]
array4 = np.asarray(list2)
print(array4)

tuple3 = (8,4,6,1,2,3)
array5 = np.asarray(tuple3).reshape(2,3)
print(array5)


[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]
[[8 4 6]
 [1 2 3]]
[1 2 3 4 5 6 7 8]
[[8 4 6]
 [1 2 3]]


## Also try np.asarray for the problem above! 

## Exercise 4:  Convert the values of Centigrade degrees into Fahrenheit degrees

Values in Fahrenheit degrees:
[ 0.   12.   45.21 34.   99.91]
Values in  Centigrade degrees:
[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


In [39]:
#without numpy

list_F = [0.0, 12.0, 45.21, 34.0, 99.91]
convert_to_C = list(map(lambda x: (x*5/9) - 32*5/9, list_F))
print(convert_to_C)

[-17.77777777777778, -11.11111111111111, 7.338888888888889, 1.1111111111111107, 37.727777777777774]


In [33]:
#using numpy
list_F = [ 0.,   12.,   45.21, 34.,   99.91]
array_F = np.asarray(list_F)
array_C = array_F*5/9 - 32*5/9
print(array_C)

[-17.77777778 -11.11111111   7.33888889   1.11111111  37.72777778]


## Exercise 5: Write a NumPy program to find the number of elements of an array, length of one array element in bytes and total bytes consumed by the elements. 

Size of the array:  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array:  24


In [40]:
array1 = np.arange(3)
print("Size of the array is ", array1.size)
print("Length of one array element in bytes: ", array1.itemsize)
print("Total bytes consumed by the elements of the array", array1.size * array1.itemsize)

Size of the array is  3
Length of one array element in bytes:  8
Total bytes consumed by the elements of the array 24


## Exercise 6: Get the unique elements of an array

Original array:
[10 10 20 20 30 30]
Unique elements of the above array:
[10 20 30]
Original array:
[[1 1]
 [2 3]]
Unique elements of the above array:
[1 2 3]


In [46]:
list1 =[10,10,20,20,30,30] 
array_orig = np.array(list1)
print("Original array: ", array_orig)
array_uniq = np.unique(array_orig)
print("Unique elements of the above array:", array_uniq)

Original array:  [10 10 20 20 30 30]
Unique elements of the above array: [10 20 30]


## Exercise 7: Change the dimension of an array


In [42]:
array1 = np.arange(1,10)
print(array1.reshape(3,3))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Exercise 8: Create a 1-D array of 30 evenly spaced elements between 2.5. and 6.5, inclusive

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


In [43]:

print(np.linspace(2.5, 6.5, 30))

[2.5        2.63793103 2.77586207 2.9137931  3.05172414 3.18965517
 3.32758621 3.46551724 3.60344828 3.74137931 3.87931034 4.01724138
 4.15517241 4.29310345 4.43103448 4.56896552 4.70689655 4.84482759
 4.98275862 5.12068966 5.25862069 5.39655172 5.53448276 5.67241379
 5.81034483 5.94827586 6.0862069  6.22413793 6.36206897 6.5       ]


## Exercise 9: Convert 1-D arrays as columns into a 2-D array

Array1: [10 20 30]
Array2: [40 50 60]
Converted array
[[10 40]
 [20 50]
 [30 60]]


In [51]:
array1 = np.arange(10, 40, 10)
array2 = np.arange(40, 70, 10)
print("Array1: ", array1)
print("Array2: ", array2)
print("Converted array \n", np.stack((array1, array2), axis=1))

Array1:  [10 20 30]
Array2:  [40 50 60]
Converted array 
 [[10 40]
 [20 50]
 [30 60]]


## Exercise 10: Create a 5x5 matrix with row values ranging from 0 to 4

Original array:
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4.
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [63]:
array_orig = np.zeros((5,5))
print("Original array: \n", array_orig)
array_modified = array_orig + np.arange(5)
print("Row values ranging from 0 to 4 \n", array_modified)

Original array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Row values ranging from 0 to 4 
 [[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


## Exercise 11: Sum of all the multiples of 3 or 5 below 100

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


In [71]:
arr1 = np.arange(3,100,3)
arr2 = np.arange(5,100,5)
combined_arr = np.concatenate((arr1,arr2))
uniq_arr = np.unique(combined_arr)
print(uniq_arr)
print(sum(uniq_arr))


[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


## Exercise 12: Combine a one and a two dimensional array together and display their elements
##### Hint : np.nditer()

One dimensional array:
[0 1 2 3]
Two dimensional array:
[[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


In [73]:
arr1 = np.arange(4)
print("One dimensional array:\n", arr1)
arr2 = np.arange(8).reshape(2,4)
print("Two dimensional array:\n", arr2)
for a,b in np.nditer([arr1, arr2]):
    print("%d:%d"%(a,b))


One dimensional array:
 [0 1 2 3]
Two dimensional array:
 [[0 1 2 3]
 [4 5 6 7]]
0:0
1:1
2:2
3:3
0:4
1:5
2:6
3:7


## Exercise 13: Write a NumPy program to replace all elements of NumPy array that are greater than specified array.

Original array:
[[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
[[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


In [77]:
list1 = [[0.42436315, 0.48558583, 0.32924763],
 [0.7439979, 0.58220701, 0.38213418],
 [0.5097581, 0.34528799, 0.1563123 ]]
arr1 = np.array(list1)
print("Original array:\n", arr1)
arr1[arr1 > 0.5] = 0.5
print("Replace all elements of the said array with .5 which are greater than .5\n", arr1)

Original array:
 [[0.42436315 0.48558583 0.32924763]
 [0.7439979  0.58220701 0.38213418]
 [0.5097581  0.34528799 0.1563123 ]]
Replace all elements of the said array with .5 which are greater than .5
 [[0.42436315 0.48558583 0.32924763]
 [0.5        0.5        0.38213418]
 [0.5        0.34528799 0.1563123 ]]


## Exercise 14: Add a new row to an empty numpy array

Empty array:
[]
After adding two new arrays:
[[10 20 30]
 [40 50 60]]


In [100]:
arr1 = np.empty((0,3), int)
print("Empty array:\n", arr1)
arr1 = np.append(arr1, np.arange(10,40,10).reshape(1,3), axis=0)
arr1 = np.append(arr1, np.array([[10,20,30]]), axis=0)
print("After adding two new arrays:\n", arr1)


Empty array:
 []
After adding two new arrays:
 [[10 20 30]
 [10 20 30]]


## Exercise 15: Write a NumPy program to join a sequence of arrays along a new axis. 

Original arrays:
[1 2 3]
[2 3 4]
Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]

Original arrays:
[[1]
 [2]
 [3]]

[[2]
 [3]
 [4]]
Sequence of arrays along a new axis:
[[1]
 [2]
 [3]
 [2]
 [3]
 [4]]


In [113]:
list1 = [1,2,3]
list2 = [2,3,4]
arr1 = np.array(list1)
arr2 = np.array(list2)
print("Original arrays:\n", arr1)
print(arr2,"\n")
print("Sequence of arrays along a new axis:")
print(np.stack((arr1, arr2)))

Original arrays:
 [1 2 3]
[2 3 4] 

Sequence of arrays along a new axis:
[[1 2 3]
 [2 3 4]]
